Fix retrieval of temperature history data (#494)
AnalogJ/scrutiny pull request #557
Opened 2023-12-18 21:59 UTC by mcarbonne

This PR allow temperature history data to be retrieved correctly, using `Index` and `Size` fields.
`collectorSmartData.AtaSctTemperatureHistory.Table` is now managed as a circular buffer, starting from `Index`.

See https://github.com/mirror/smartmontools/blob/master/ataprint.cpp (`ataPrintSCTTempHist` function).
For more details: https://github.com/AnalogJ/scrutiny/issues/494#issuecomment-1861412724

Note: this is still a draft, as I haven't fully tested it yet.

2024-01-02 19:26 UTC, mcarbonne commented
Also, to mitigate this change, the default `COLLECTOR_CRON_SCHEDULE` might be reduced from one day to one hour (`COLLECTOR_CRON_SCHEDULE=0 * * * *`).

2024-03-14 07:37 UTC, mcarbonne commented
@AnalogJ I'd like to have your feedback on this PR.
My proposal was to simply remove temperature history retrieval because of its lack of robustness (cf. my arguments above) but If you don't agree, I can update my PR to add an option to disable this feature instead of removing it.

Here is a screenshot of my temperature history graph (with temperature history retrieval enabled) :
![image](https://github.com/AnalogJ/scrutiny/assets/46689813/2bb93485-259c-4bac-b092-dd60e66cb68e)
Obviously, there is something wrong with the temperature history of the green one.

2024-07-19 03:14 UTC, AnalogJ commented
Hey @mcarbonne appreciate your work here -- but yeah I'd rather add a switch to enable/disable it, rather than remove it completely

2024-07-19 17:45 UTC, mcarbonne commented
> Hey @mcarbonne appreciate your work here -- but yeah I'd rather add a switch to enable/disable it, rather than remove it completely

Thanks for you feedback. I have updated my PR with your suggestions but I have not yet been able to test this change: I have build issues (npm related) but haven't found out if it's related to my changes but it is similar to the nightly build issue. I'll try to investigate when I have time.

2024-07-21 12:31 UTC, mcarbonne commented
@AnalogJ build is working again, feature is behaving as expected, docker image is available (ghcr.io/mcarbonne/scrutiny:master-omnibus). Feel free to give me your feedback.

2024-08-04 10:19 UTC, mcarbonne commented
@AnalogJ PR updated :)

2024-11-28 18:54 UTC, helgehatt commented
Would be great if this could get merged anytime soon.

2025-01-04 22:24 UTC, AnalogJ commented
This looks good, let me check why the CI isn't running.

2025-01-11 09:21 UTC, mcarbonne commented
I did some testing on my fork and indeed, workflows need a little update. I included it in my PR (commit b7d57c03d5a2752b98b493d9c21b2ec261b39da1).

This is mandatory according to documentation:
https://github.com/actions/upload-artifact


> In matrix scenarios, be careful to not accidentally upload to the same artifact, or else you will encounter conflict errors. It would be best to name the artifact with a prefix or suffix from the matrix:
> 
> jobs:
>   upload:
>     name: Generate Build Artifacts
> 
>     strategy:
>       matrix:
>         os: [ubuntu-latest, windows-latest]
>         version: [a, b, c]
> 
>     runs-on: ${{ matrix.os }}
> 
>     steps:
>     - name: Build
>       run: ./some-script --version=${{ matrix.version }} > my-binary
>     - name: Upload
>       uses: actions/upload-artifact@v4
>       with:
>         name: binary-${{ matrix.os }}-${{ matrix.version }}
>         path: my-binary
> 
> This will result in artifacts like: binary-ubuntu-latest-a, binary-windows-latest-b, and so on.

2025-10-13 15:42 UTC, ssorgatem commented
so how's the merging of this looking?

2026-02-02 09:44 UTC, mcarbonne commented
@kaysond I've cleaned the history of my PR ! (rebase and squash).
Let me know if you agree with my changes and/or if further changes are needed.
Note : this feature has been tested and running for a while in my fork and also several other forks.

2026-02-02 20:47 UTC, kaysond commented
> @kaysond I've cleaned the history of my PR ! (rebase and squash). Let me know if you agree with my changes and/or if further changes are needed. Note : this feature has been tested and running for a while in my fork and also several other forks.

Thanks! Took a quick look from my phone and don't have any immediate concerns. I do think it would be nice to have this be a per-drive setting, but obviously things aren't set up to accommodate that.

My only thought is to rename the config option to something more user-friendly. Without documentation it may not be obvious to people that it doesn't fully disable temp logging...

2026-02-03 19:04 UTC, mcarbonne commented
I added a tooltip + a dedicated section for this kind of options :
<img width="1009" height="468" alt="tooltip" src="https://github.com/user-attachments/assets/c3ed3302-a9a9-409c-980b-bee56b8e4d5c" />

I agree that a per device option would be better but the current software structure is limited right now.

2026-02-05 00:34 UTC, kaysond requested changes
Looks good. Tooltip and quirks section is a good idea.

I know it's pedantic, but could you please update the variable names, UI, etc to use "discard" instead of "retrieve"? (Note that this also means the default should be FALSE). I think it's more clear and more accurate since the data is technically always retrieved. I also prefer that it's something that has to be enabled rather than disabled, which I think makes more sense for all quirks...

I'm open to a different word if you can think of a better one...

2026-02-05 00:34 UTC, kaysond commented on webapp/frontend/src/app/layout/common/dashboard-settings/dashboard-settings.component.html
> +                matTooltip="Retrieve historical temperature data from the drive's SCT log. This feature might be bugged on some drives."
```suggestion
                matTooltip="Discard historical temperature data retrieved from the SMART Command Transport (SCT) Data Table, which may be inaccurate for some drives. The current temperature is always stored."
```

2026-02-05 12:16 UTC, mcarbonne commented on webapp/frontend/src/app/layout/common/dashboard-settings/dashboard-settings.component.html
> +                matTooltip="Retrieve historical temperature data from the drive's SCT log. This feature might be bugged on some drives."
I updated my PR with your suggestion.

~~I also noticed something strange, not related to my changes, in the tests: some tests seems to always pass.
I did a quick POC in another branch on my fork : https://github.com/mcarbonne/scrutiny/commit/0f0e7082063a85644b60f7d77fb250562c45993b~~
```
	fakeConfig.EXPECT().GetBool("user.collector.discard_sct_temp_history").Return(false).AnyTimes()
	fakeConfig.EXPECT().GetBool("user.collector.discard_sct_temp_history").Return(true).AnyTimes()
```
~~But the pipeline is passing on this branch :upside_down_face:~~

EDIT: I did a little digging; this isn't a bug, but the test itself. I'm not very familiar with gomock, but it seems AnyTimes() allows the test to pass even if the function is never called.

2026-02-05 18:28 UTC, kaysond approved these changes
LGTM! Thanks for the updates and for your contribution. I'm going to do a sanity check deployment later today then will merge this.

2026-02-06 04:59 UTC, merged