Better Docker Compose example
AnalogJ/scrutiny pull request #685
Opened 2024-09-09 19:44 UTC by enoch85

Version is not needed anymore, also added TZdata and HealthCheck + upped InfluxDB to 2.7

2025-01-04 22:27 UTC, AnalogJ commented on docs/INSTALL_HUB_SPOKE.md
> +      retries: 20
is this necessary? I think there's a healthcheck built into the image.

2025-01-05 01:53 UTC, enoch85 commented on docs/INSTALL_HUB_SPOKE.md
> +      retries: 20
Not sure actually, but let's remove it. :)

2025-01-13 09:41 UTC, enoch85 commented
@AnalogJ Please have another look

2026-02-05 00:42 UTC, kaysond commented
@enoch85 - I'm ok with these changes except the influxdb version. That should go in a separate PR and include significant testing (and we'd likely go to the most recent release). 

If you want to rebase this and update accordingly I can merge.

2026-02-05 05:17 UTC, enoch85 commented
> @enoch85 - I'm ok with these changes except the influxdb version. That should go in a separate PR and include significant testing (and we'd likely go to the most recent release).
> 
> If you want to rebase this and update accordingly I can merge.

I don't know if "significant testing" is the same thing as "running in prod since 9 sep 2024"? 😅

2026-02-05 18:33 UTC, kaysond commented
> > @enoch85 - I'm ok with these changes except the influxdb version. That should go in a separate PR and include significant testing (and we'd likely go to the most recent release).
> > If you want to rebase this and update accordingly I can merge.
> 
> I don't know if "significant testing" is the same thing as "running in prod since 9 sep 2024"? 😅

Fair enough. I meant more for a major version update. Assuming there's no migration needed of the DB files, might as well bump to 2.8.0 then.

There are a handful more places that version needs to be updated though, including the github CI workflow. If you search the repo for "influxdb", it should be pretty obvious where to make all the updates. Then I'm happy to review and run the new version myself as well for testing.

2026-02-22 05:03 UTC, kaysond commented
@enoch85 can you please rebase this?

2026-02-22 09:17 UTC, enoch85 commented
Sorry! Forgot about this, will do it right away!

2026-02-22 10:43 UTC, enoch85 commented
@kaysond Should be good now.

Left the version at 2.7 as it's the only one I tested.

2026-02-22 15:57 UTC, kaysond requested changes
Thanks for the updates. Would you mind making these changes please? Would've done it myself but the code editing is impossible on mobile whereas PR reviews are doable...

2026-02-22 15:57 UTC, kaysond commented on docs/INSTALL_HUB_SPOKE.md
> +    image: influxdb:2.7-alpine
Please bump to 2.8 (the rest of the docs have been bumped too ;I've been running no issues.

2026-02-22 15:57 UTC, kaysond commented on docs/INSTALL_HUB_SPOKE.md
> +      # Optional but highly recommended to notify you in case of a problem
```suggestion
      # Optional but highly recommended to notify you in case of a problem; space-separated list of shoutrrr uri's
```

2026-02-22 15:57 UTC, kaysond commented on docs/INSTALL_HUB_SPOKE.md
> +      - SCRUTINY_NOTIFY_URLS=[ smtp://myname%40example%2Ecom:124%4034%241@ms.my.domain.com:587 ]
```suggestion
      - SCRUTINY_NOTIFY_URLS=http://gotify:80/message?token=a-gotify-token ntfy://username:password@host:port/topic
```

The array formsf is actually incorrect

2026-02-22 16:02 UTC, enoch85 commented
@kaysond Ready to merge?

2026-02-22 16:03 UTC, kaysond approved these changes

2026-02-22 16:06 UTC, merged

2026-02-22 16:07 UTC, kaysond commented
Thanks for the contribution!